### ISSUE TITLE
Single argument for input parameters to ApiData() function

### ISSUE THREAD

**Issue by mafw** [statisticsnorway/PxWebApiData#5]
Personally I think it would be "better" if  the `ApiData()` function had a single argument that you supplied with a named list of input parameters.  Something like this:
```
ApiData(12056, param = list(ContentsCode = "Barn i barnehage (antall)", KOKeierforhold0000 = c("Kommune")))
```
The reason I believe this is better is because you have one single argument that applies to every table. As I am very inexperienced when it comes to R package development, however, it might be that this is a bad idea for other reasons?

**Comment by olangsrud** [comment]
The functionality you want is achieved with the function do.call.
`z <- do.call("ApiData", c(12056, list(ContentsCode = "Barn i barnehage (antall)", KOKeierforhold0000 = c("Kommune"))))`
or
`z <- do.call("ApiData", list(12056, ContentsCode = "Barn i barnehage (antall)", KOKeierforhold0000 = c("Kommune")))`
